title: "mildmelon.github.io"
description: "Caidan Williams' Blog & Portfolio"

google_analytics: UA-149931368-3
resume_link: https://docs.google.com/viewer?url=https://docs.google.com/document/d/1pOsL216fx-liQRvFX8MyQI7xWcA9HGSJ-DonPrMEVlo/export?format=pdf

header_pages:
  - index.md
  - blog.md
  - contact.md

footer:
  - name: GitHub
    link: https://github.com/mildmelon
  - name: Twitter
    link: https://twitter.com/_mildmelon
  - name: LinkedIn
    link: https://www.linkedin.com/in/caidan-williams/
  - name: RSS
    link: https://mildmelon.github.io/feed.xml

style: dark # dark (default) or light
# listen_for_clients_preferred_style: true # true or false (default)

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-seo-tag
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: Caidan Williams