title: "mildmelon.github.io"
description: "Caidan Williams' Blog & Portfolio"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author: Caidan Williams

include:
  - .well-known

header_pages:
  - index.md
  - blog.md
  - portfolio.md
  - contact.md

footer:
  - name: GitHub
    link: https://github.com/mildmelon
  - name: Twitter
    link: https://twitter.com/_mildmelon
  - name: LinkedIn
    link: https://www.linkedin.com/in/caidan-williams
  - name: Digital Garden
    link: https://caidanwilliams.com/digital-garden
  - name: RSS
    link: https://mildmelon.github.io/feed.xml

collections:
  projects:
    output: true
    permalink: /projects/:path/

style: dark # dark (default) or light
# listen_for_clients_preferred_style: true # true or false (default)

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-seo-tag
  - jekyll-feed

##### Custom variables #####

about_me_tags:
  - developer
  - artist
  - musician
  - human named Caidan

resume_link: https://registry.jsonresume.org/mildmelon
google_analytics: UA-149931368-3

# Dirty hack to use Google Forms as a backend to recieve contact submissions
gf_url: https://docs.google.com/forms/d/e/1FAIpQLSfIvvG20D5MFqQze8FrBEq3-pgN2vI2ViAk4QlM2_qzkythAg/formResponse
gf_name: entry.2005620554
gf_email: entry.1045781291
gf_message: entry.839337160
gf_gotcha: entry.1961620496
