google_analytics: UA-149931368-3

header_pages:
  - index.md
  - about.md

footer: 'follow me on <a href="https://twitter.com/_mildmelon">twitter</a>'

style: dark # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

theme: jekyll-theme-console

plugins:
  - jekyll-seo-tag
